# Generated by Django 4.2.5 on 2024-07-06 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio_app', '0004_skill'),
    ]

    operations = [
        migrations.CreateModel(
            name='Projects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('projectname', models.CharField(max_length=100)),
                ('projectdesc', models.TextField()),
                ('live_demo', models.URLField()),
                ('github_repo', models.URLField()),
                ('technologies', models.CharField(max_length=50)),
            ],
        ),
    ]
