# Generated by Django 4.2.5 on 2024-07-07 07:42

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio_app', '0009_alter_link_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projects',
            name='projectdesc',
            field=tinymce.models.HTMLField(),
        ),
    ]
