# Generated by Django 4.2.5 on 2024-07-07 09:11

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio_app', '0010_alter_projects_projectdesc'),
    ]

    operations = [
        migrations.CreateModel(
            name='Name_Details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('my_name', models.CharField(max_length=100)),
                ('my_profession', models.CharField(max_length=100)),
                ('my_profession_details', tinymce.models.HTMLField()),
            ],
        ),
    ]
